"""Add field hire_date to employee table

Revision ID: 03cc70d57969
Revises: d413a7f1bf28
Create Date: 2024-09-10 21:06:10.371245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cc70d57969'
down_revision = 'd413a7f1bf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('hire_date')

    # ### end Alembic commands ###
